# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gowtham/workspace/ferryfair

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gowtham/workspace/ferryfair

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/gowtham/workspace/ferryfair/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\" \"examples\" \"libraries\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gowtham/workspace/ferryfair/CMakeFiles /home/gowtham/workspace/ferryfair/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gowtham/workspace/ferryfair/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ferryfair

# Build rule for target.
ferryfair: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ferryfair
.PHONY : ferryfair

# fast build rule for target.
ferryfair/fast:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/build
.PHONY : ferryfair/fast

#=============================================================================
# Target rules for targets named ferrybaseStatic

# Build rule for target.
ferrybaseStatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ferrybaseStatic
.PHONY : ferrybaseStatic

# fast build rule for target.
ferrybaseStatic/fast:
	$(MAKE) -f ferrybase/CMakeFiles/ferrybaseStatic.dir/build.make ferrybase/CMakeFiles/ferrybaseStatic.dir/build
.PHONY : ferrybaseStatic/fast

#=============================================================================
# Target rules for targets named ferrybase

# Build rule for target.
ferrybase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ferrybase
.PHONY : ferrybase

# fast build rule for target.
ferrybase/fast:
	$(MAKE) -f ferrybase/CMakeFiles/ferrybase.dir/build.make ferrybase/CMakeFiles/ferrybase.dir/build
.PHONY : ferrybase/fast

#=============================================================================
# Target rules for targets named loggerStatic

# Build rule for target.
loggerStatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 loggerStatic
.PHONY : loggerStatic

# fast build rule for target.
loggerStatic/fast:
	$(MAKE) -f logger/CMakeFiles/loggerStatic.dir/build.make logger/CMakeFiles/loggerStatic.dir/build
.PHONY : loggerStatic/fast

#=============================================================================
# Target rules for targets named logger

# Build rule for target.
logger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logger
.PHONY : logger

# fast build rule for target.
logger/fast:
	$(MAKE) -f logger/CMakeFiles/logger.dir/build.make logger/CMakeFiles/logger.dir/build
.PHONY : logger/fast

#=============================================================================
# Target rules for targets named IteratorIncrement

# Build rule for target.
IteratorIncrement: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IteratorIncrement
.PHONY : IteratorIncrement

# fast build rule for target.
IteratorIncrement/fast:
	$(MAKE) -f FFJSON/CMakeFiles/IteratorIncrement.dir/build.make FFJSON/CMakeFiles/IteratorIncrement.dir/build
.PHONY : IteratorIncrement/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ContinuousSubmit.dir/build.make FFJSON/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ContinuousCoverage.dir/build.make FFJSON/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ContinuousTest.dir/build.make FFJSON/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ContinuousBuild.dir/build.make FFJSON/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ContinuousUpdate.dir/build.make FFJSON/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ContinuousStart.dir/build.make FFJSON/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f FFJSON/CMakeFiles/NightlyUpdate.dir/build.make FFJSON/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f FFJSON/CMakeFiles/NightlyBuild.dir/build.make FFJSON/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f FFJSON/CMakeFiles/Continuous.dir/build.make FFJSON/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named FFJSONStatic

# Build rule for target.
FFJSONStatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FFJSONStatic
.PHONY : FFJSONStatic

# fast build rule for target.
FFJSONStatic/fast:
	$(MAKE) -f FFJSON/CMakeFiles/FFJSONStatic.dir/build.make FFJSON/CMakeFiles/FFJSONStatic.dir/build
.PHONY : FFJSONStatic/fast

#=============================================================================
# Target rules for targets named FFJSON

# Build rule for target.
FFJSON: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FFJSON
.PHONY : FFJSON

# fast build rule for target.
FFJSON/fast:
	$(MAKE) -f FFJSON/CMakeFiles/FFJSON.dir/build.make FFJSON/CMakeFiles/FFJSON.dir/build
.PHONY : FFJSON/fast

#=============================================================================
# Target rules for targets named TestFFJSON

# Build rule for target.
TestFFJSON: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestFFJSON
.PHONY : TestFFJSON

# fast build rule for target.
TestFFJSON/fast:
	$(MAKE) -f FFJSON/CMakeFiles/TestFFJSON.dir/build.make FFJSON/CMakeFiles/TestFFJSON.dir/build
.PHONY : TestFFJSON/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ContinuousMemCheck.dir/build.make FFJSON/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f FFJSON/CMakeFiles/Nightly.dir/build.make FFJSON/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f FFJSON/CMakeFiles/NightlyTest.dir/build.make FFJSON/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f FFJSON/CMakeFiles/NightlyStart.dir/build.make FFJSON/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f FFJSON/CMakeFiles/NightlyMemoryCheck.dir/build.make FFJSON/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f FFJSON/CMakeFiles/NightlyMemCheck.dir/build.make FFJSON/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ExperimentalStart.dir/build.make FFJSON/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ContinuousConfigure.dir/build.make FFJSON/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f FFJSON/CMakeFiles/NightlyCoverage.dir/build.make FFJSON/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ExperimentalUpdate.dir/build.make FFJSON/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ExperimentalConfigure.dir/build.make FFJSON/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ExperimentalCoverage.dir/build.make FFJSON/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ExperimentalBuild.dir/build.make FFJSON/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f FFJSON/CMakeFiles/NightlyConfigure.dir/build.make FFJSON/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ExperimentalTest.dir/build.make FFJSON/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ExperimentalMemCheck.dir/build.make FFJSON/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f FFJSON/CMakeFiles/Experimental.dir/build.make FFJSON/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f FFJSON/CMakeFiles/NightlySubmit.dir/build.make FFJSON/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f FFJSON/CMakeFiles/ExperimentalSubmit.dir/build.make FFJSON/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named test-fuzxy

# Build rule for target.
test-fuzxy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-fuzxy
.PHONY : test-fuzxy

# fast build rule for target.
test-fuzxy/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/test-fuzxy.dir/build.make libwebsockets/CMakeFiles/test-fuzxy.dir/build
.PHONY : test-fuzxy/fast

#=============================================================================
# Target rules for targets named test-server

# Build rule for target.
test-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-server
.PHONY : test-server

# fast build rule for target.
test-server/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/test-server.dir/build.make libwebsockets/CMakeFiles/test-server.dir/build
.PHONY : test-server/fast

#=============================================================================
# Target rules for targets named websockets_shared

# Build rule for target.
websockets_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 websockets_shared
.PHONY : websockets_shared

# fast build rule for target.
websockets_shared/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/websockets_shared.dir/build.make libwebsockets/CMakeFiles/websockets_shared.dir/build
.PHONY : websockets_shared/fast

#=============================================================================
# Target rules for targets named websockets

# Build rule for target.
websockets: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 websockets
.PHONY : websockets

# fast build rule for target.
websockets/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/websockets.dir/build.make libwebsockets/CMakeFiles/websockets.dir/build
.PHONY : websockets/fast

#=============================================================================
# Target rules for targets named test-fraggle

# Build rule for target.
test-fraggle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-fraggle
.PHONY : test-fraggle

# fast build rule for target.
test-fraggle/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/test-fraggle.dir/build.make libwebsockets/CMakeFiles/test-fraggle.dir/build
.PHONY : test-fraggle/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/dist.dir/build.make libwebsockets/CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named test-ping

# Build rule for target.
test-ping: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-ping
.PHONY : test-ping

# fast build rule for target.
test-ping/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/test-ping.dir/build.make libwebsockets/CMakeFiles/test-ping.dir/build
.PHONY : test-ping/fast

#=============================================================================
# Target rules for targets named test-server-extpoll

# Build rule for target.
test-server-extpoll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-server-extpoll
.PHONY : test-server-extpoll

# fast build rule for target.
test-server-extpoll/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/test-server-extpoll.dir/build.make libwebsockets/CMakeFiles/test-server-extpoll.dir/build
.PHONY : test-server-extpoll/fast

#=============================================================================
# Target rules for targets named test-echo

# Build rule for target.
test-echo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-echo
.PHONY : test-echo

# fast build rule for target.
test-echo/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/test-echo.dir/build.make libwebsockets/CMakeFiles/test-echo.dir/build
.PHONY : test-echo/fast

#=============================================================================
# Target rules for targets named test-server-pthreads

# Build rule for target.
test-server-pthreads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-server-pthreads
.PHONY : test-server-pthreads

# fast build rule for target.
test-server-pthreads/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/test-server-pthreads.dir/build.make libwebsockets/CMakeFiles/test-server-pthreads.dir/build
.PHONY : test-server-pthreads/fast

#=============================================================================
# Target rules for targets named test-client

# Build rule for target.
test-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-client
.PHONY : test-client

# fast build rule for target.
test-client/fast:
	$(MAKE) -f libwebsockets/CMakeFiles/test-client.dir/build.make libwebsockets/CMakeFiles/test-client.dir/build
.PHONY : test-client/fast

FerryStream.o: FerryStream.cpp.o

.PHONY : FerryStream.o

# target to build an object file
FerryStream.cpp.o:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/FerryStream.cpp.o
.PHONY : FerryStream.cpp.o

FerryStream.i: FerryStream.cpp.i

.PHONY : FerryStream.i

# target to preprocess a source file
FerryStream.cpp.i:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/FerryStream.cpp.i
.PHONY : FerryStream.cpp.i

FerryStream.s: FerryStream.cpp.s

.PHONY : FerryStream.s

# target to generate assembly for a file
FerryStream.cpp.s:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/FerryStream.cpp.s
.PHONY : FerryStream.cpp.s

WSServer.o: WSServer.cpp.o

.PHONY : WSServer.o

# target to build an object file
WSServer.cpp.o:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/WSServer.cpp.o
.PHONY : WSServer.cpp.o

WSServer.i: WSServer.cpp.i

.PHONY : WSServer.i

# target to preprocess a source file
WSServer.cpp.i:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/WSServer.cpp.i
.PHONY : WSServer.cpp.i

WSServer.s: WSServer.cpp.s

.PHONY : WSServer.s

# target to generate assembly for a file
WSServer.cpp.s:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/WSServer.cpp.s
.PHONY : WSServer.cpp.s

global.o: global.cpp.o

.PHONY : global.o

# target to build an object file
global.cpp.o:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/global.cpp.o
.PHONY : global.cpp.o

global.i: global.cpp.i

.PHONY : global.i

# target to preprocess a source file
global.cpp.i:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/global.cpp.i
.PHONY : global.cpp.i

global.s: global.cpp.s

.PHONY : global.s

# target to generate assembly for a file
global.cpp.s:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/global.cpp.s
.PHONY : global.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ferryfair.dir/build.make CMakeFiles/ferryfair.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... ferryfair"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... ferrybaseStatic"
	@echo "... ferrybase"
	@echo "... loggerStatic"
	@echo "... logger"
	@echo "... IteratorIncrement"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousUpdate"
	@echo "... ContinuousStart"
	@echo "... NightlyUpdate"
	@echo "... NightlyBuild"
	@echo "... Continuous"
	@echo "... FFJSONStatic"
	@echo "... FFJSON"
	@echo "... TestFFJSON"
	@echo "... ContinuousMemCheck"
	@echo "... Nightly"
	@echo "... NightlyTest"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ContinuousConfigure"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalUpdate"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalBuild"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... Experimental"
	@echo "... NightlySubmit"
	@echo "... ExperimentalSubmit"
	@echo "... test-fuzxy"
	@echo "... test-server"
	@echo "... websockets_shared"
	@echo "... websockets"
	@echo "... test-fraggle"
	@echo "... dist"
	@echo "... test-ping"
	@echo "... test-server-extpoll"
	@echo "... test-echo"
	@echo "... test-server-pthreads"
	@echo "... test-client"
	@echo "... FerryStream.o"
	@echo "... FerryStream.i"
	@echo "... FerryStream.s"
	@echo "... WSServer.o"
	@echo "... WSServer.i"
	@echo "... WSServer.s"
	@echo "... global.o"
	@echo "... global.i"
	@echo "... global.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

